version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: university_courses
      MYSQL_USER: php_user
      MYSQL_PASSWORD: php_password
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  php-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: php_app
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: